filename: mocks.go
packages:
    github.com/seacite-tech/compendium/user-service/internal/service:
        interfaces:
            AuthService:
            UserService:
    github.com/seacite-tech/compendium/user-service/internal/email:
        interfaces:
            EmailSender:
