filename: mocks.go
packages:
    github.com/compendium-tech/compendium/user-service/internal/service:
        interfaces:
            AuthService:
            UserService:
    github.com/compendium-tech/compendium/email-delivery-service/pkg/email:
        interfaces:
            EmailSender:
    github.com/compendium-tech/compendium/user-service/internal/email:
        interfaces:
            EmailMessageBuilder:
