filename: mocks.go
packages:
    github.com/compendium-tech/compendium/user-service/internal/service:
        interfaces:
            AuthService:
            UserService:
    github.com/compendium-tech/compendium/user-service/internal/email:
        interfaces:
            MessageBuilder:
            Sender:
    github.com/compendium-tech/compendium/user-service/internal/ua:
        interfaces:
            UserAgentParser:
    github.com/compendium-tech/compendium/user-service/internal/geoip:
        interfaces:
            GeoIP:
